# Generated by Django 5.2.3 on 2025-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('device_age', models.PositiveIntegerField(help_text='Device age in months')),
                ('storage_capacity', models.CharField(max_length=20)),
                ('ram_capacity', models.CharField(max_length=20)),
                ('battery_cycle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_health', models.FloatField(blank=True, null=True)),
                ('storage_usage', models.FloatField(blank=True, null=True)),
                ('ram_usage', models.FloatField(blank=True, null=True)),
                ('fast_charging', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('charges_overnight', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('previous_repairs', models.JSONField(blank=True, default=list)),
                ('last_repair_date', models.DateField(blank=True, null=True)),
                ('authorized_service', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('warranty_status', models.CharField(blank=True, choices=[('in', 'In Warranty'), ('out', 'Out of Warranty')], max_length=20)),
                ('overheating', models.BooleanField(default=False)),
                ('drop_history', models.BooleanField(default=False)),
                ('water_damage', models.BooleanField(default=False)),
                ('sensor_issues', models.BooleanField(default=False)),
                ('battery_bulging', models.BooleanField(default=False)),
                ('screen_cracked', models.BooleanField(default=False)),
                ('buttons_not_working', models.BooleanField(default=False)),
                ('screen_time', models.CharField(blank=True, max_length=10)),
                ('primary_use', models.JSONField(blank=True, default=list)),
                ('charge_frequency', models.CharField(blank=True, max_length=20)),
                ('charge_time', models.CharField(blank=True, max_length=20)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('region_temp', models.FloatField(blank=True, null=True)),
                ('updated_software', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('rooted', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Not Sure')], max_length=10)),
                ('major_concern', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
